### ISSUE TITLE
Add ability to provide custom meta-data with rules

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmnlint#18]
Allow rules to contain additional meta-data, such as a description, documentation URL and so on.

### Task

* [ ] Extend rules to offer meta-data
  * [ ] Documentation URL (https://github.com/camunda/camunda-modeler/issues/4491)
* [ ] Meta-data is provided during reporting

Hint: checkout an [e.g. of an eslint rule](https://github.com/eslint/eslint/blob/master/lib/rules/accessor-pairs.js)

**Comment by nikku** [comment]
Released with [`v11.2.0`](https://github.com/bpmn-io/bpmnlint/releases/tag/v11.2.0)
